# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html>
<html lang=\"en\" data-theme=\"dark\">
  <head>
    <meta charset=\"UTF-8\" />
    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />
    <title>PicoPump</title>
    <link rel=\"stylesheet\" href=\"https://static.drebollo.dev/PicoPump/css/pico.min.css\" />
    <link rel=\"stylesheet\" href=\"https://static.drebollo.dev/PicoPump/css/custom.css\" />
  </head>
  <body>
    <!-- Nav -->
    <nav class=\"container-fluid\">
      <ul>
        <li>
          <a href=\"/\" class=\"contrast\"><strong>PicoPump Web Tool</strong></a>
        </li>
      </ul>
      <ul>
        <li><a href=\"/login\" class=\"secondary\">Login</a></li>
      </ul>
    </nav>
    <!-- Nav -->
    <!-- Main -->
    <main class=\"container main-container\">
      <figure>
        <img src=\"https://static.drebollo.dev/PicoPump/css/img.png\" alt=\"Water Pump\" />
      </figure>
      <article>
        <div class=\"error\"><h1>ERROR 404</h1></div>
      </article>
    </main>
    <!-- Main -->
    <!-- Footer -->
    <footer class=\"container-fluid\">
      <small
        >© 2022
        <a href=\"https://drebollo.dev\" class=\"secondary\"
          >Diego Rebollo</a
        ></small
      >
    </footer>
    <!-- ./ Footer -->
  </body>
</html>
"""
