# Autogenerated file
def render(vars_file, session_status, water_sensor_readout, last_run_date, threshold, realy_status, date):
    # Autogenerated file
    def render1(*a, **d):
        yield """<!DOCTYPE html>
<html lang=\"en\" data-theme=\"dark\">
  <head>
    <meta charset=\"UTF-8\" />
    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />
    <title>PicoPump</title>
    <link rel=\"stylesheet\" href=\"https://static.drebollo.dev/PicoPump/css/pico.min.css\" />
    <link rel=\"stylesheet\" href=\"https://static.drebollo.dev/PicoPump/css/custom.css\" />
  </head>
  <body>
    <!-- Nav -->
    <nav class=\"container-fluid\">
      <ul>
        <li>
          <a href=\"/\" class=\"contrast\"><strong>PicoPump Web Tool</strong></a>
        </li>
      </ul>
      <ul>
        """
        if (session_status) is None:
            yield """    
        <li><a class=\"secondary\" href=\"/login\">Login</a></li>              
        """
        else:
            yield """        <li><a class=\"secondary\" href=\"/logout\">Logout</a></li>
        """
        yield """      </ul>
    </nav>
    <!-- Nav -->"""
    yield from render1()
    yield """   
   <!-- Main -->
    <main class=\"container main-container\">
        <figure>
          <img src=\"https://static.drebollo.dev/PicoPump/css/img.png\" alt=\"Water Pump\" />
        </figure>
        <article>
          <table>
            <tbody>
              <tr>
                <td>Status:</td>
                <td>
                """
    if (realy_status) is False:
        yield """                    Not Running
                """
    elif (realy_status) is None:
        yield """                    None (main function not running)
                """
    else:
        yield """                    Running
                """
    yield """            </td>
              </tr>
              <tr>
                <td>Last Time Running:</td>
                <td>"""
    yield str(last_run_date)
    yield """</td>
              </tr>
              <tr>
                <td>Water Sensor Readout:</td>
                <td>"""
    yield str(water_sensor_readout)
    yield """ - (Threshold: """
    yield str(threshold)
    yield """)</td>
              </tr>
              """
    if (session_status) is 'authorized':
        yield """              <tr>
                <td>
                  <a href=\"/relayon\" class=\"btn\">Relay ON</a>
                </td>
                <td>
                  <a href=\"/relayoff\" class=\"btn\">Relay OFF</a>
                </td>
              </tr>
              <tr>
                <td>
                  Date:              
                </td>
                <td>
                  """
        yield str(date)
        yield """
                </td>
              </tr>
              <tr>
                <td>
                  Seconds Readout:              
                </td>
                <td>
                  """
        yield str(vars_file['seconds_readout'])
        yield """
                </td>
              </tr>
              <tr>
                <td>
                  Seconds Pumping:
                </td>
                <td>
                  """
        yield str(vars_file['seconds_pumping'])
        yield """
                </td>
              </tr>
              <tr>
                <td>
                  Relay Pin:
                </td>
                <td>
                  """
        yield str(vars_file['relay_pin'])
        yield """
                </td>
              </tr>
              <tr>
                <td>
                  Sensor Pin:
                </td>
                <td>
                  """
        yield str(vars_file['sensor_pin'])
        yield """
                </td>
              </tr>
              </tbody>
              </table>
              <div class=\"squash\">
                <p>Parameters:</p>
                <form method=\"post\">               
                    <select name=\"var_name\">
                    """
        for key in (vars_file):
            yield """                        <option value="""
            yield str(key)
            yield """>
                        """
            yield str(key)
            yield """
                        </option>
                    """
        yield """                    </select>
                    <p><label for=\"new_value\">New Value:</label></p>
                    <p><input type=\"number\" id=\"new_value\" name=\"new_value\" autocomplete=\"off\" required size=\"3\"></p>
                  <input type=\"submit\" value=\"Save\">
                 </form>
              </div>  
              """
    yield """                    
            </tbody>
          </table>
        </article>  
      </main>
      <!-- Main -->
"""
# Autogenerated file
    def render2(*a, **d):
        yield """    <!-- Footer -->
    <footer class=\"container-fluid\">
        <small
          >© 2022
          <a href=\"https://drebollo.dev\" class=\"secondary\"
            >Diego Rebollo</a
          ></small
        >
      </footer>
      <!-- ./ Footer -->
    </body>
  </html>
  """
    yield from render2()
