# Autogenerated file
def render(session_status, sensor_readout, latest, threshold, status):
    # Autogenerated file
    def render1(*a, **d):
        yield """<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>PicoPump</title>
    <!-- CSS only -->
    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\" crossorigin=\"anonymous\">
    <!-- JavaScript Bundle with Popper -->
    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3\" crossorigin=\"anonymous\"></script>
</head>
<body style=\"background-color:rgb(41, 47, 56);\" class=\"d-flex flex-column h-100\">    
    <nav class=\"navbar navbar-expand-sm navbar-dark bg-dark\">
        <div class=\"container-fluid\">
          <a class=\"navbar-brand\" href=\"/\">PicoPump Web Manage Tool</a>
          <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#mynavbar\">
            <span class=\"navbar-toggler-icon\"></span>
          </button>
          <div class=\"collapse navbar-collapse\" id=\"mynavbar\">
            <ul class=\"navbar-nav ms-auto\">
              <li class=\"nav-item\">
              """
        if (session_status) is None:
            yield """                  
                  <a class=\"nav-link\" href=\"/login\">Login</a>
              """
        else:
            yield """                  <a class=\"nav-link\" href=\"/logout\">Logout</a>
              """
        yield """              
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <main class=\"flex-shrink-0\">
        <div class=\"container\">
"""
    yield from render1()
    yield """          <img src=\"https://i.postimg.cc/9fcr6V3Q/pic.png\" class=\"img-fluid mt-3 mx-auto d-block\" alt=\"water pump\">       
          <div class=\"w-auto p-3\">
            <ul class=\"list-group\">
              <li class=\"list-group-item list-group-item-dark\">Water Sensor Read: """
    yield str(sensor_readout)
    yield """ (Threshold: """
    yield str(threshold)
    yield """)</li>
              <li class=\"list-group-item list-group-item-dark\"><form method=\"post\"><button class='btn btn-secondary' name='relay' value='on' type=\"submit\">Reley ON</button><button class='btn btn-secondary' name='relay' value='off' type=\"submit\">Reley OFF</button></form></li>
              <li class=\"list-group-item list-group-item-dark\">Last time: """
    yield str(latest)
    yield """</li>
              <li class=\"list-group-item list-group-item-dark\">Status: """
    yield str(status)
    yield """</li>
            </ul>
          </div>
"""
# Autogenerated file
    def render2(*a, **d):
        yield """</div>        
</main>      
<footer class=\"footer mt-auto py-2 bg-dark\">
  <div class=\"container\">
    <span class=\"text-muted\">Copyright © 2022</span>          
  </div>
</footer>   
</body>
</html>"""
    yield from render2()
